
CREATE TABLE IF NOT EXISTS role (
    role_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(35) NOT NULL UNIQUE,
    PRIMARY KEY (role_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS users (
    users_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    username VARCHAR(35) NOT NULL UNIQUE,
    password VARCHAR(72) NOT NULL,
    fullname VARCHAR(100) NOT NULL UNIQUE,
    role INT UNSIGNED NOT NULL,
    PRIMARY KEY (users_id),
    FOREIGN KEY (role) REFERENCES role(role_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS trade (

) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS bidlist (

) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS curvepoint (

) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS rating (

) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS rulename (

) ENGINE=InnoDB;
